---
# JOB TEMPLATE NOTE:
# - Expects contact_success_hosts from previous workflow step
# - Creates VM snapshots with proper error handling

- name: Validate hosts available for snapshot creation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if contact testing produced any successful hosts
      ansible.builtin.fail:
        msg: "No hosts available for snapshot creation - contact_success_hosts is empty"
      when: contact_success_hosts | default([]) | length == 0

    - name: Create dynamic inventory group for snapshot creation
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups: "snapshot_targets"
        vm_folder: "{{ vm_folder_map[item] | default('') }}"
        vm_name_resolved: "{{ vm_name_map[item] | default(item) }}"
      loop: "{{ contact_success_hosts | default([]) }}"

- name: Take concurrent VM snapshots and wait for completion
  hosts: snapshot_targets
  gather_facts: false
  vars:
    vmware_validate_certs: "{{ vmware_validate_certs | default(true) }}"
    snapshot_label: "{{ snapshot_label | default('Patching') }}"
    snapshot_name_expected: "{{ snapshot_name_expected | default('automated-snapshot_' ~ snapshot_label ~ '_' ~ lookup('pipe','date +%Y%m%d-%H%M%S')) }}"
    snapshot_quiesce: "{{ snapshot_quiesce | default(false) }}"
    snapshot_memory_dump: "{{ snapshot_memory_dump | default(true) }}"
    snapshot_async_timeout: "{{ snapshot_async_timeout | default(10800) }}"  # 3h
    snapshot_poll_interval: "{{ snapshot_poll_interval | default(60) }}"     # seconds
  tasks:
    - name: Refresh VM folder/name information from vCenter
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: "{{ vmware_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name_resolved | default(hostvars[inventory_hostname].vm_name | default(inventory_hostname)) }}"
      register: vm_info_refresh
      delegate_to: localhost
      failed_when: false

    - name: Start VM snapshot creation asynchronously
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: "{{ vmware_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_info_refresh.instance.hw_folder | default(vm_folder) }}"
        name: "{{ vm_info_refresh.instance.hw_name | default(vm_name_resolved) }}"
        state: present
        snapshot_name: "{{ snapshot_name_expected }}"
        quiesce: "{{ snapshot_quiesce }}"
        memory_dump: "{{ snapshot_memory_dump }}"
      async: "{{ snapshot_async_timeout }}"
      poll: 0
      register: snap_async
      delegate_to: localhost
      failed_when: false
      when:
        - not (vm_info_refresh.failed | default(false))
        - vm_info_refresh.instance is defined

    - name: Wait for snapshot creation to complete
      ansible.builtin.async_status:
        jid: "{{ snap_async.ansible_job_id }}"
      register: snap_wait
      until: (snap_wait.finished | default(0)) | int == 1
      retries: "{{ (snapshot_async_timeout | int // snapshot_poll_interval | int) + 1 }}"
      delay: "{{ snapshot_poll_interval | int }}"
      delegate_to: localhost
      failed_when: false
      when: snap_async.ansible_job_id is defined

    - name: Cleanup async job files
      ansible.builtin.async_status:
        jid: "{{ snap_async.ansible_job_id }}"
        mode: cleanup
      delegate_to: localhost
      changed_when: false
      failed_when: false
      when: snap_async.ansible_job_id is defined

    - name: Record successful snapshot results
      ansible.builtin.set_stats:
        data:
          snapshot_success_hosts: "{{ snapshot_success_hosts | default([]) + [inventory_hostname] }}"
          snapshot_name_map: >-
            {{
              snapshot_name_map | default({}) | combine({
                inventory_hostname: snapshot_name_expected
              })
            }}
        aggregate: true
        per_host: false
      when: >
        snap_async.ansible_job_id is defined and
        not (snap_wait.failed | default(false)) and
        (snap_wait.rc | default(1)) == 0 and
        not (snap_async.failed | default(false))

    - name: Record failed snapshot results
      ansible.builtin.set_stats:
        data:
          snapshot_failed_hosts: "{{ snapshot_failed_hosts | default([]) + [inventory_hostname] }}"
          snapshot_failure_reasons: >-
            {{
              snapshot_failure_reasons | default({}) | combine({
                inventory_hostname: snap_wait.stderr | default(snap_async.msg | default('Unknown snapshot error'))
              })
            }}
        aggregate: true
        per_host: false
      when: >
        vm_info_refresh.failed | default(false) or
        snap_async.failed | default(false) or
        snap_wait.failed | default(false) or
        (snap_wait.rc | default(1)) != 0

    - name: Display snapshot results for this host
      ansible.builtin.debug:
        msg: |
          Host:{{ inventory_hostname }}
          VM Info Refresh: {{ 'SUCCESS' if not (vm_info_refresh.failed | default(false)) else 'FAILED' }}
          {% set snapshot_success = (snap_async.ansible_job_id is defined and not (snap_wait.failed | default(false)) and (snap_wait.rc | default(1)) == 0) %}
          Snapshot Creation: {{ 'SUCCESS' if snapshot_success else 'FAILED' }}
          Snapshot Name: {{ snapshot_name_expected }}
          {% if snap_wait.failed | default(false) or snap_async.failed | default(false) %}
          Error: {{ snap_wait.stderr | default(snap_async.msg | default('Unknown error')) }}
          {% endif %}

- name: Store snapshot name for later workflow steps
  hosts: localhost
  gather_facts: false
  run_once: true
  tasks:
    - name: Publish snapshot name for verification step
      ansible.builtin.set_stats:
        data:
          snapshot_name_expected: "{{ snapshot_name_expected }}"
        aggregate: true
        per_host: false

    - name: Display snapshot phase summary
      ansible.builtin.debug:
        msg: |
          ========================================
          SNAPSHOT PHASE COMPLETED
          ========================================
          Target Hosts: {{ contact_success_hosts | default([]) | length }}
          Successful: {{ snapshot_success_hosts | default([]) | length }}
          Failed: {{ snapshot_failed_hosts | default([]) | length }}
          {% if contact_success_hosts | default([]) | length > 0 %}
          Success Rate: {{ ((snapshot_success_hosts | default([]) | length) * 100.0 / (contact_success_hosts | default([]) | length)) | round(1) }}%
          {% else %}
          Success Rate: 0%
          {% endif %}
          Snapshot Name: {{ snapshot_name_expected | default('Not created') }}
          ========================================
          Successful Hosts: {{ snapshot_success_hosts | default([]) | join(', ') }}
          Failed Hosts: {{ snapshot_failed_hosts | default([]) | join(', ') }}
          ========================================
