---
# JOB TEMPLATE NOTE:
# - Inventory: localhost only
# - Extra vars required: gitlab_repo_url, gitlab_token
# - Optional: gitlab_branch, gitlab_user_name, gitlab_user_email, publish_base_path

- name: Publish reports to GitLab repository using Access Token
  hosts: localhost
  gather_facts: true
  vars:
    # GitLab repository configuration
    gitlab_repo_url: "{{ gitlab_repo_url | mandatory }}"  # e.g., https://gitlab.company.com/ops/patch-reports.git
    gitlab_token: "{{ gitlab_token | mandatory }}"        # GitLab access token (store in AAP vault)
    gitlab_branch: "{{ gitlab_branch | default('main') }}"
    gitlab_user_name: "{{ gitlab_user_name | default('AAP Automation') }}"
    gitlab_user_email: "{{ gitlab_user_email | default('aap-automation@company.com') }}"
    publish_base_path: "{{ publish_base_path | default('patch-reports') }}"

    # Source paths from previous report step (published by 07-report.yml via set_stats)
    source_report_dir: "{{ ex_report_dir | default('') }}"
    source_report_file: "{{ ex_report_file | default('') }}"
    
    # Local repository path for GitLab operations
    repo_local_path: "/tmp/gitlab_repo_{{ ex_run_ts | default(ansible_date_time.epoch) }}"

    # Construct authenticated GitLab URL (OAuth token for HTTPS)
    gitlab_auth_url: >-
      {{
        gitlab_repo_url | regex_replace('^https://', 'https://oauth2:' + gitlab_token + '@')
        if gitlab_repo_url.startswith('https://')
        else gitlab_repo_url
      }}

  tasks:
    - name: Validate required variables
      assert:
        that:
          - gitlab_repo_url is defined and gitlab_repo_url != ""
          - gitlab_token is defined and gitlab_token != ""
          - gitlab_repo_url.startswith('https://')
          - source_report_dir is defined and source_report_dir != ""
          - gitlab_user_name is defined and gitlab_user_name != ""
          - gitlab_user_email is defined and gitlab_user_email != ""
          - publish_base_path is defined and publish_base_path != ""
        fail_msg: |
          Missing or invalid required variables:
            - gitlab_repo_url must be HTTPS URL (e.g., https://gitlab.company.com/user/repo.git)
            - gitlab_token must be valid GitLab access token
            - source_report_dir must exist from previous report step
            - gitlab_user_name and gitlab_user_email must be provided

    - name: Validate source report paths
      assert:
        that:
          - source_report_dir != ""
          - not source_report_dir.startswith("/tmp/")  # Prevent temp path issues
          - ex_run_date is defined
          - ex_run_ts is defined
        fail_msg: "Invalid source report paths or missing execution metadata"

    - name: Debug incoming report variables
      debug:
        msg:
          - "ex_report_dir={{ ex_report_dir | default('<undefined>') }}"
          - "ex_report_root={{ ex_report_root | default('<undefined>') }}"
          - "ex_report_file={{ ex_report_file | default('<undefined>') }}"
          - "ex_run_date={{ ex_run_date | default('<undefined>') }}"
          - "ex_run_ts={{ ex_run_ts | default('<undefined>') }}"
          - "source_report_dir={{ source_report_dir }}"
          - "repo_local_path={{ repo_local_path }}"

    - name: Check if source report directory exists
      stat:
        path: "{{ source_report_dir }}"
      register: source_dir_stat

    - name: Fail if source reports not found
      fail:
        msg: >-
          Source report directory '{{ source_report_dir }}' not found.
          Ensure the report generation step ran successfully before publish.
      when: not source_dir_stat.stat.exists

    - name: Find CSV report files
      find:
        paths: "{{ source_report_dir }}"
        patterns: "*.csv"
        recurse: true
      register: csv_files

    - name: Find HTML report files
      find:
        paths: "{{ source_report_dir }}"
        patterns: "*.html"
        recurse: true
      register: html_files

    - name: Validate that reports were found
      assert:
        that:
          - (csv_files.files | length) > 0 or (html_files.files | length) > 0
        fail_msg: "No CSV or HTML reports found in {{ source_report_dir }}"

    - name: Ensure git is configured globally (fallback)
      shell: |
        git config --global user.name "{{ gitlab_user_name }}" 2>/dev/null || true
        git config --global user.email "{{ gitlab_user_email }}" 2>/dev/null || true
      changed_when: false
      ignore_errors: true

    - name: Ensure local repo parent directory exists
      file:
        path: "{{ repo_local_path | dirname }}"
        state: directory
        mode: "0755"
        recurse: true

    - name: Check if repo already exists (has .git)
      stat:
        path: "{{ repo_local_path }}/.git"
      register: repo_stat

    - name: Clone or update GitLab repository
      git:
        repo: "{{ gitlab_auth_url }}"
        dest: "{{ repo_local_path }}"
        version: "{{ gitlab_branch }}"
        update: true
        force: true
        accept_hostkey: true
        depth: 1  # Shallow clone for efficiency
      register: git_operation
      no_log: true  # Hide token from logs
      retries: 3
      delay: 5
      until: git_operation is succeeded

    - name: Verify Git operation succeeded
      fail:
        msg: "Git operation failed: {{ git_operation.msg | default('Unknown git error') }}"
      when: 
        - git_operation is defined
        - git_operation.failed | default(false)

    - name: Configure Git identity for this repo
      shell: |
        cd "{{ repo_local_path }}"
        git config user.name "{{ gitlab_user_name }}"
        git config user.email "{{ gitlab_user_email }}"
      changed_when: false

    - name: Ensure publication folder for this run exists
      file:
        path: "{{ repo_local_path }}/{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}"
        state: directory
        mode: "0755"
        recurse: true

    - name: Copy CSV files to GitLab repo
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_local_path }}/{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}/{{ item.path | basename }}"
        mode: "0644"
      loop: "{{ csv_files.files }}"
      when: csv_files.files | length > 0
      register: csv_copy_results

    - name: Copy HTML report files to GitLab repo
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_local_path }}/{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}/{{ item.path | basename }}"
        mode: "0644"
      loop: "{{ html_files.files }}"
      when: html_files.files | length > 0
      register: html_copy_results

    - name: Create per-run README index (Markdown)
      copy:
        dest: "{{ repo_local_path }}/{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}/README.md"
        mode: "0644"
        content: |
          # AAP Patch Workflow Report - {{ ex_run_ts | default(ansible_date_time.epoch) }}

          **Generated:** {{ lookup('pipe', 'date -Iseconds') | default(ansible_date_time.iso8601) }}
          **Workflow Execution:** {{ ex_run_date | default(ansible_date_time.date) }} {{ ex_run_ts | default(ansible_date_time.epoch) }}

          ## Files in this Report

          ### Summary Reports
          {% for file in html_files.files %}
          - **[{{ file.path | basename }}]({{ file.path | basename }})** - Executive summary with success rates and phase breakdown
          {% endfor %}

          ### Detailed CSV Reports (Engineering Data)
          {% for file in csv_files.files %}
          - **{{ file.path | basename }}** - {{ file.path | basename | replace('_', ' ') | replace('.csv', '') | title }} host list
          {% endfor %}

          ## Workflow Statistics

          {% if ansible_stats.data.health_success_hosts is defined and ansible_stats.data.health_failed_hosts is defined %}
          - **Total Hosts:** {{ (ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length) }}
          - **Successful:** {{ ansible_stats.data.health_success_hosts | default([]) | length }} ({{ ((ansible_stats.data.health_success_hosts | default([]) | length) * 100.0 / ((ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length))) | round(1) if ((ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length)) > 0 else 0.0 }}%)
          - **Failed:** {{ ansible_stats.data.health_failed_hosts | default([]) | length }} ({{ ((ansible_stats.data.health_failed_hosts | default([]) | length) * 100.0 / ((ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length))) | round(1) if ((ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length)) > 0 else 0.0 }}%)
          {% endif %}

          {% if ansible_stats.data.snapshot_name_expected is defined %}
          - **Snapshot Name:** `{{ ansible_stats.data.snapshot_name_expected }}`
          {% endif %}

          ## Navigation

          - **[Latest Reports](../)** - Browse other reports from {{ ex_run_date | default(ansible_date_time.date) }}
          - **[All Reports](../../)** - Browse all historical patch reports

          ---
          *Generated by AAP Patch Automation*
      register: readme_create_result

    - name: Publish to GitLab (stage, commit, push, report)
      block:
        - name: Stage all changes for commit
          shell: |
            cd "{{ repo_local_path }}"
            git add --all "{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}/"
          changed_when: false
          register: git_add_result

        - name: Detect if any staged changes exist
          shell: |
            cd "{{ repo_local_path }}"
            git diff --staged --quiet || echo "CHANGED"
          register: staged
          changed_when: false
          failed_when: false

        - name: Show what will be committed
          shell: |
            cd "{{ repo_local_path }}"
            git diff --staged --name-status
          register: staged_files
          changed_when: false
          when: staged.stdout == "CHANGED"

        - name: Display staged files
          debug:
            msg: "Files to be committed: {{ staged_files.stdout_lines | default([]) | join(', ') }}"
          when: staged.stdout == "CHANGED"

        - name: Commit staged changes (only when needed)
          shell: |
            cd "{{ repo_local_path }}"
            git commit -m "Automated publication for {{ ex_run_date | default(ansible_date_time.date) }} {{ ex_run_ts | default(ansible_date_time.epoch) }}

            - Generated {{ csv_files.files | length }} CSV file(s)
            - Generated {{ html_files.files | length }} HTML report(s)
            {% if ansible_stats.data.health_success_hosts is defined and ansible_stats.data.health_failed_hosts is defined -%}
            - Processed {{ (ansible_stats.data.health_success_hosts | default([]) | length) + (ansible_stats.data.health_failed_hosts | default([]) | length) }} total host(s)
            - {{ ansible_stats.data.health_success_hosts | default([]) | length }} successful, {{ ansible_stats.data.health_failed_hosts | default([]) | length }} failed
            {%- endif %}
            
            Automated by: {{ gitlab_user_name }} <{{ gitlab_user_email }}>"
          when: staged.stdout == "CHANGED"
          register: git_commit
          changed_when: >
            git_commit.rc == 0 and
            (git_commit.stdout is search('file\\(s\\)? changed|insertion\\(s\\)?|deletion\\(s\\)?'))

        - name: Push commit to GitLab using access token
          shell: |
            cd "{{ repo_local_path }}"
            git push "{{ gitlab_auth_url }}" "{{ gitlab_branch }}"
          when: staged.stdout == "CHANGED"
          register: git_push
          no_log: true
          retries: 3
          delay: 10
          until: git_push is succeeded
          changed_when: >
            git_push.rc == 0 and
            (git_push.stdout is not search('Everything up-to-date'))
          failed_when: git_push.rc != 0

        - name: Verify push operation
          debug:
            msg: |
              Push operation completed:
              - Return code: {{ git_push.rc | default('N/A') }}
              - Output: {{ git_push.stdout | default('No output') }}
          when: staged.stdout == "CHANGED"

        - name: Calculate GitLab URLs for this run
          set_fact:
            gitlab_base_url: "{{ gitlab_repo_url | regex_replace('\\.git$', '') }}"
            report_web_path: "{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}"
            report_html_name: >-
              {{
                (html_files.files | map(attribute='path') | map('basename') | list | first | default('report.html'))
              }}

        - name: Publish GitLab URLs and counts to workflow (set_stats)
          set_stats:
            data:
              gitlab_report_url: "{{ gitlab_base_url }}/-/tree/{{ gitlab_branch }}/{{ report_web_path }}"
              gitlab_html_url: "{{ gitlab_base_url }}/-/blob/{{ gitlab_branch }}/{{ report_web_path }}/{{ report_html_name }}"
              gitlab_raw_html_url: "{{ gitlab_base_url }}/-/raw/{{ gitlab_branch }}/{{ report_web_path }}/{{ report_html_name }}"
              gitlab_base_url: "{{ gitlab_base_url }}"
              publish_status: "success"
              published_files_count: "{{ (csv_files.files | length) + (html_files.files | length) + 1 }}"  # +1 for README
              files_committed: "{{ 'true' if staged.stdout == 'CHANGED' else 'false' }}"
            aggregate: true
            per_host: false

        - name: Display publication results
          debug:
            msg: |
              ========================================
              PUBLICATION SUCCESSFUL
              ========================================
              Repository: {{ gitlab_repo_url }}
              Branch: {{ gitlab_branch }}
              Report Path: {{ report_web_path }}
              
              📊 View Reports: {{ gitlab_base_url }}/-/tree/{{ gitlab_branch }}/{{ report_web_path }}
              📄 HTML Report: {{ gitlab_base_url }}/-/blob/{{ gitlab_branch }}/{{ report_web_path }}/{{ report_html_name }}
              🔗 Direct HTML: {{ gitlab_base_url }}/-/raw/{{ gitlab_branch }}/{{ report_web_path }}/{{ report_html_name }}
              
              Files Published: {{ csv_files.files | length }} CSV, {{ html_files.files | length }} HTML, 1 README
              Changes Committed: {{ 'Yes' if staged.stdout == 'CHANGED' else 'No (no changes detected)' }}
              Published: {{ lookup('pipe', 'date -Iseconds') | default(ansible_date_time.iso8601) }}
              ========================================

      rescue:
        - name: Capture detailed error information
          set_fact:
            error_details: |
              Git operation error details:
              - ansible_failed_result: {{ ansible_failed_result | default({}) | to_nice_json }}
              - git_operation: {{ git_operation | default({}) | to_nice_json }}
              - git_add_result: {{ git_add_result | default({}) | to_nice_json }}
              - git_commit: {{ git_commit | default({}) | to_nice_json }}
              - git_push: {{ git_push | default({}) | to_nice_json }}

        - name: Mark publication failure (set_stats)
          set_stats:
            data:
              publish_status: "failed"
              publish_error: "{{ ansible_failed_result.msg | default('Unknown error during GitLab publication') }}"
              publish_error_details: "{{ error_details }}"
            aggregate: true
            per_host: false

        - name: Display failure information
          debug:
            msg: |
              ========================================
              PUBLICATION FAILED
              ========================================
              Error: {{ ansible_failed_result.msg | default('Unknown error') }}
              Repo: {{ gitlab_repo_url }}
              Branch: {{ gitlab_branch }}
              Local Path: {{ repo_local_path }}
              Time: {{ lookup('pipe', 'date -Iseconds') | default(ansible_date_time.iso8601) }}
              
              Error Details:
              {{ error_details | default('No additional details available') }}
              ========================================

        - name: Re-raise failure to stop workflow
          fail:
            msg: "GitLab publication failed: {{ ansible_failed_result.msg | default('Unknown error') }}"

      always:
        - name: List files that were staged (for debugging)
          shell: |
            cd "{{ repo_local_path }}" 2>/dev/null && find "{{ publish_base_path }}/{{ ex_run_date | default(ansible_date_time.date) }}/{{ ex_run_ts | default(ansible_date_time.epoch) }}" -type f 2>/dev/null || echo "Directory not accessible"
          register: final_files
          ignore_errors: true
          changed_when: false

        - name: Show final file list
          debug:
            msg: "Files in publication directory: {{ final_files.stdout_lines | default(['None found']) }}"
          ignore_errors: true

        - name: Cleanup temporary repository
          file:
            path: "{{ repo_local_path }}"
            state: absent
          ignore_errors: true

        - name: Final publication status
          debug:
            msg: |
              Final Status: {{ publish_status | default('unknown') }}
              Cleanup completed for: {{ repo_local_path }}